### ISSUE TITLE
Header bar styling gap

### ISSUE THREAD

**Issue by jordanwillis** [maroonshade/teacosy#2]
This feedback is just a little nit picky thing 😉 

I noticed that there is a very small gap between the top of your fixed header that becomes noticeable when you scroll down in the page.  This gap is present because all browsers assign default CSS property values to elements, including the `<body>`.  If you use Chrome and inspect the `<body>` element using DevTools, you will see that there is a `margin: 8px` under the "User Agent Stylesheet" section (which means this is the default).

You can eliminate this gap with the below CSS:

``` css
body {
  margin: 0;
  background-color: black;
  font-family: "Helvetica", sans-serif;
  color: seashell;
  font-size: 22px;
  text-align: center;
}
```
