### ISSUE TITLE
CSS Review

### ISSUE THREAD

**Issue by jordanwillis** [maroonshade/teacosy#3]
Speaking of my last feedback (about the header gap, I wanted to also discuss the rest of the properties that I proposed with the `body` selector.

``` css
body {
  margin: 0;
  background-color: black;
  font-family: "Helvetica", sans-serif;
  color: seashell;
  font-size: 22px;
  text-align: center;
}
```

In almost all cases, I would recommend assigning page level styles (e.g. background color, font color, alignment, etc.) on the `<body>` element (which will be inherited by most sub-elements) instead of using the wildcard (*) selector.

https://github.com/maroonshade/teacosy/blob/f76f07e5e8b4f0ccf5371b39f3ed434c5792cc0d/resources/css/style.css#L3-L11

While they appear to have a similar behavior, the primary difference is the approach I recommend achieves the result using CSS inheritance rules.  Instead, the wildcard approach applies these properties to *all* elements that don't otherwise match another rule.  So you can end up with things getting styled that you really didn't want to, and that is why you end up having to create additional rules like this (see below) to exclude things.

https://github.com/maroonshade/teacosy/blob/f76f07e5e8b4f0ccf5371b39f3ed434c5792cc0d/resources/css/style.css#L15-L17

It also turns out that from a performance perspective, the wildcard rule is the slowest to get applied.  Again, because it causes the browser to process through each element in your HTML and add these styles where a more specific rule doesn't already match.
